import {} from 'react'

function Home(){
  return(
    <>
    <h1>Bem Vindo à nossa loja</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod venenatis ante vel suscipit. Proin porttitor pharetra tellus et blandit. Aliquam ut sapien vel quam hendrerit consequat a suscipit urna. Integer porta bibendum turpis, non lobortis orci malesuada et. Ut commodo lacus vitae odio vestibulum, at dictum quam fringilla. Morbi pretium euismod nibh, a lacinia lorem euismod id. Quisque dui felis, rhoncus in diam id, viverra commodo dolor.

      Donec varius finibus turpis ut interdum. Morbi volutpat velit sit amet erat vulputate, a tempor nunc fermentum. Proin porttitor tortor vitae laoreet euismod. Integer et dui venenatis lorem auctor scelerisque eget nec eros. Ut non venenatis turpis, nec pharetra arcu. Sed porttitor consequat sodales. Vivamus volutpat diam nisl, et eleifend justo finibus sit amet.

      Duis malesuada lorem a dictum pharetra. Quisque feugiat metus elit, sed congue quam consequat id. Mauris in tellus ullamcorper, fermentum arcu non, elementum nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed at neque eleifend, pellentesque massa sed, pellentesque ligula. Etiam pellentesque arcu sed ante volutpat scelerisque. Fusce sit amet vehicula leo.

      Aliquam vel ligula ornare, egestas felis non, fermentum mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque ultrices eget leo et bibendum. Nam fringilla non lacus et bibendum. In fermentum non sapien at accumsan. Maecenas faucibus et felis non pulvinar. Vivamus pretium mi sodales, cursus tortor quis, sodales justo. Proin euismod augue vitae ipsum congue, vitae viverra odio lacinia. Nullam vel tristique magna, sit amet gravida erat. Donec non urna sit amet risus pellentesque fermentum id a dolor. Etiam in neque massa.

      Nullam pharetra vel sapien vel dignissim. In pretium, est eget tempus maximus, urna ante commodo lacus, vitae iaculis augue turpis ac massa. Phasellus efficitur nibh ultrices purus tempor bibendum. Aliquam sit amet malesuada sapien. Etiam vestibulum ullamcorper lorem, a iaculis tellus. Donec blandit risus et libero finibus fringilla. Sed sit amet pellentesque dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris vitae tortor felis. Sed lorem purus, tristique eu dapibus ac, dictum sit amet ipsum. Aenean porttitor volutpat ante, in scelerisque leo viverra vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rutrum sollicitudin lectus, vitae auctor dui convallis vel. Suspendisse blandit mauris posuere euismod tempus.

      Aliquam sodales lacus vel mauris ullamcorper, vitae vehicula leo egestas. Curabitur non turpis at est semper vehicula vitae ac ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ipsum turpis, congue non suscipit et, eleifend volutpat tellus. Aenean auctor, neque non consequat mollis, magna libero semper magna, in tempor tortor magna sed lectus. Donec eu orci at felis egestas tempus. Mauris auctor augue a sodales ornare. Duis interdum, purus ut fermentum placerat, nisl felis rhoncus ipsum, non condimentum tellus purus et leo. Aliquam porttitor ex non ipsum gravida dignissim tincidunt in risus. Vestibulum lacinia, massa a sodales porttitor, metus est dignissim neque, vestibulum viverra elit orci eu sem. Proin vitae urna sodales, tincidunt mi quis, varius turpis. Cras viverra nisl id libero commodo, et vestibulum tellus volutpat. Maecenas tincidunt mi lacus, vitae vehicula est facilisis et. Curabitur pretium mi vitae dui tristique, vitae dictum velit pharetra. Duis ligula diam, dapibus at leo venenatis, tristique mattis lorem.

      Nam laoreet tincidunt lorem, ut lacinia eros volutpat id. Phasellus at nulla condimentum, eleifend enim id, ullamcorper lorem. Duis porttitor odio eu risus fermentum aliquam. Nullam eu augue ut mauris tincidunt cursus. Nulla nisi nunc, malesuada at ante sit amet, maximus egestas orci. Nam ultricies tincidunt sodales. Pellentesque odio ante, dapibus rutrum orci sed, ultrices viverra quam. Vestibulum in est ut elit aliquam faucibus. Donec malesuada aliquam mi eu pharetra. Etiam ut dictum elit. Proin ut efficitur quam, ut pharetra mi. Donec ac dui eget lectus mollis dignissim eu eget elit. Phasellus at ante vulputate arcu dignissim gravida. Integer vitae massa diam.

      Duis mollis tristique augue, quis pellentesque ligula molestie a. Aliquam ligula sem, aliquet sit amet rhoncus sed, commodo a lectus. Cras ornare interdum suscipit. Vestibulum vehicula felis odio, sit amet vestibulum tortor sagittis vel. Duis at quam est. Praesent non neque ac nisi semper lobortis. Donec malesuada risus in cursus porta. Integer vitae enim ut neque luctus lobortis. In non elementum nibh. Nulla lacinia sapien lorem, eget faucibus nunc gravida feugiat. Vestibulum sit amet magna a ex commodo varius vitae eget sem. Praesent imperdiet vestibulum arcu et lacinia.

      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod venenatis ante vel suscipit. Proin porttitor pharetra tellus et blandit. Aliquam ut sapien vel quam hendrerit consequat a suscipit urna. Integer porta bibendum turpis, non lobortis orci malesuada et. Ut commodo lacus vitae odio vestibulum, at dictum quam fringilla. Morbi pretium euismod nibh, a lacinia lorem euismod id. Quisque dui felis, rhoncus in diam id, viverra commodo dolor.

      Donec varius finibus turpis ut interdum. Morbi volutpat velit sit amet erat vulputate, a tempor nunc fermentum. Proin porttitor tortor vitae laoreet euismod. Integer et dui venenatis lorem auctor scelerisque eget nec eros. Ut non venenatis turpis, nec pharetra arcu. Sed porttitor consequat sodales. Vivamus volutpat diam nisl, et eleifend justo finibus sit amet.

      Duis malesuada lorem a dictum pharetra. Quisque feugiat metus elit, sed congue quam consequat id. Mauris in tellus ullamcorper, fermentum arcu non, elementum nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed at neque eleifend, pellentesque massa sed, pellentesque ligula. Etiam pellentesque arcu sed ante volutpat scelerisque. Fusce sit amet vehicula leo.

      Aliquam vel ligula ornare, egestas felis non, fermentum mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque ultrices eget leo et bibendum. Nam fringilla non lacus et bibendum. In fermentum non sapien at accumsan. Maecenas faucibus et felis non pulvinar. Vivamus pretium mi sodales, cursus tortor quis, sodales justo. Proin euismod augue vitae ipsum congue, vitae viverra odio lacinia. Nullam vel tristique magna, sit amet gravida erat. Donec non urna sit amet risus pellentesque fermentum id a dolor. Etiam in neque massa.

      Nullam pharetra vel sapien vel dignissim. In pretium, est eget tempus maximus, urna ante commodo lacus, vitae iaculis augue turpis ac massa. Phasellus efficitur nibh ultrices purus tempor bibendum. Aliquam sit amet malesuada sapien. Etiam vestibulum ullamcorper lorem, a iaculis tellus. Donec blandit risus et libero finibus fringilla. Sed sit amet pellentesque dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris vitae tortor felis. Sed lorem purus, tristique eu dapibus ac, dictum sit amet ipsum. Aenean porttitor volutpat ante, in scelerisque leo viverra vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin rutrum sollicitudin lectus, vitae auctor dui convallis vel. Suspendisse blandit mauris posuere euismod tempus.

      Aliquam sodales lacus vel mauris ullamcorper, vitae vehicula leo egestas. Curabitur non turpis at est semper vehicula vitae ac ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ipsum turpis, congue non suscipit et, eleifend volutpat tellus. Aenean auctor, neque non consequat mollis, magna libero semper magna, in tempor tortor magna sed lectus. Donec eu orci at felis egestas tempus. Mauris auctor augue a sodales ornare. Duis interdum, purus ut fermentum placerat, nisl felis rhoncus ipsum, non condimentum tellus purus et leo. Aliquam porttitor ex non ipsum gravida dignissim tincidunt in risus. Vestibulum lacinia, massa a sodales porttitor, metus est dignissim neque, vestibulum viverra elit orci eu sem. Proin vitae urna sodales, tincidunt mi quis, varius turpis. Cras viverra nisl id libero commodo, et vestibulum tellus volutpat. Maecenas tincidunt mi lacus, vitae vehicula est facilisis et. Curabitur pretium mi vitae dui tristique, vitae dictum velit pharetra. Duis ligula diam, dapibus at leo venenatis, tristique mattis lorem.

      Nam laoreet tincidunt lorem, ut lacinia eros volutpat id. Phasellus at nulla condimentum, eleifend enim id, ullamcorper lorem. Duis porttitor odio eu risus fermentum aliquam. Nullam eu augue ut mauris tincidunt cursus. Nulla nisi nunc, malesuada at ante sit amet, maximus egestas orci.

      
    </p>
    </>
  )
}
export default Home